default:
  logger: &logger
    name: webot
    #level 'CRITICAL','ERROR','WARNING','INFO','DEBUG'

development:
  scraper:
    #controller_count & sockets = 20:
    #  almost the most efficient, it wont scale up much even increase the count
    globalMaxSockets: 20
    cluster_mode: 1
    controller_count: 20
    retry_count: 0
  logger:
    <<: *logger
    file_log:
      filename: debug_log.log
      level: WARN
    stdout_log:
      level: WARN
  selenium:
    type: remote
    remote_server_path: http://192.168.33.1:4444/wd/hub
    #proxy_host: 36.238.87.236
    #proxy_port: 3128
  mongo:
    database: webot_development
    host: 127.0.0.1
    port: 27017
  beanstalkd:
    tube_name: node_promise_scraper_development
    host: 127.0.0.1
    port: 11300
